//! Golden-vector kind **`fine-tree`** (task G15): the fine-tree/GGM vectors,
//! whose reason for existing is to pin **MSB-first GGM leaf indexing**.
//!
//! Spec basis: the GGM fine tree and its normative cover rule (MVP-SPEC.md
//! line 96), the Merkle definitions with `0x00`/`0x01` domain separation and
//! RFC 6962 unbalanced promotion (line 78), the M0 milestone (line 153), and
//! Verification's **unbalanced-n golden vector** (line 169).
//!
//! # Why a vector kind rather than a `testdata/fine-tree/` tree
//!
//! tasks/G.md G15 sketches `testdata/fine-tree/`. Q2's layout decision makes
//! `testdata/vectors/<format-version>/` the home of *all* committed vectors,
//! Q6's freeze registry already carries the must-exist obligation under the
//! slug `fine-tree-unbalanced-n6`, and `testdata/vectors/README.md` reserved
//! the kind name `fine-tree` for exactly this task. Landing here therefore
//! clears that obligation and inherits, for free: the discovery contract, the
//! NON-SECRET enforcement, the misfiled-version check, the three-OS
//! `cross-os-*` lanes, Q6's per-version freeze, and the WASM-safe execution
//! path the Q5 native↔WASM bit-match lane reuses — exactly as C15's
//! `sig-reject` and C16's four kinds did. `testdata/fine-tree/README.md`
//! already anticipated this ("… may additionally land as `fine-tree` kind
//! vector files under `../vectors/<format-version>/`").
//!
//! # What the document pins
//!
//! For each case (`n = 6` unbalanced, `n = 1` root-is-leaf, `n = 0` no tree,
//! `n = 5` one past a power of two):
//!
//! - **every used GGM node seed** — the complete set of grid nodes covering
//!   at least one real leaf, so an indexing change is visible at every level
//!   and not only at the root;
//! - **every `salt_i`** — this is the MSB-first pin: reversing the bit order
//!   changes `salt_i` for every index whose bit pattern is not a palindrome;
//! - **every RFC 6962 content-tree node** under unbalanced promotion, each
//!   with the canonical grid slot its wire address would use, ordered by
//!   subtree width then first leaf (i.e. level by level from the leaves up);
//! - **`fine_root`**;
//! - and per opening the **full range proof**: the leaf-exact cover with its
//!   seeds, and the boundary Merkle path with its hashes.
//!
//! # How it is checked
//!
//! [`build_expect`] recomputes the *entire* `expect` object from `inputs`
//! through antseal-core's public API and the document is compared as a whole,
//! so a missing, extra, or reordered entry fails as loudly as a wrong byte.
//! On top of that, [`execute`] runs the assertions a value comparison cannot
//! express:
//!
//! 1. **MSB-first divergence** — the LSB-first walk is performed explicitly
//!    and must produce a *different* salt for every index whose reversed path
//!    differs. Without this, a document generated by an LSB-first
//!    implementation would be self-consistent.
//! 2. **Unused slots are never derived** — every grid node lying wholly at or
//!    past `n` must be refused by [`SaltTree::seed_at`], and the pinned node
//!    set must be exactly its complement.
//! 3. **Every opening verifies** — each proof is run back through
//!    [`verify_range`] (G13), so the vectors are openings that actually open.
//! 4. **`n = 0` has no tree at all** — asserted against the four entry points
//!    that must decline it.
//!
//! The `expect` values themselves are cross-checked against an **independent
//! implementation**: `testdata/vectors/v1/fine-tree/gen_vectors.py` rebuilds
//! the identical document from MVP-SPEC.md using the Python standard library
//! only, sharing no code with this crate.

use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::content::fine_tree::build::{leaf_hash, node_hash, rfc6962_split};
use crate::content::fine_tree::proof::canonical_slot;
use crate::content::{
    ByteRange, NodeAddress, RangeProof, SaltTree, child_seed, cover_seeds, depth_for_leaf_count,
    minimal_cover, prove_range, rebuild_fine_root,
};
use crate::crypto::material::{Salt16, Seed32};

use super::vectors::{RECOMPUTED_DIGEST_DOMAIN, VectorError, VectorSummary, decode_hex, hex};
use super::{TEST_MASTER_SECRET_W, alternate_test_secret};

/// The registered kind name.
pub const KIND: &str = "fine-tree";

/// The documented label of the synthetic file seed:
/// `s_root = SHA-256(S_ROOT_LABEL ‖ TEST_MASTER_SECRET_W)`.
///
/// The G15 task calls for "a fixed synthetic `s_root`". Inventing a fresh
/// 32-byte literal would breach the secret-material convention's "every
/// fixture secret is the documented seed or deterministically derived from
/// it" (`testdata/README.md`), so the seed is minted through the project's
/// [`alternate_test_secret`] construction instead: fixed, synthetic, clearly
/// labelled, and reproducible by any implementation reading this formula.
///
/// The label is a domain separator, not a secret: it appears verbatim in the
/// committed vector's `inputs.s_root_label`.
pub const S_ROOT_LABEL: &str = "antseal G15 fine-tree s_root";

/// Beyond this slot count the executor stops sweeping *every* grid node for
/// the unused-slot assertion. The committed cases all sit at `d <= 3`; the
/// bound exists so a future large-`n` case cannot turn the sweep quadratic.
const EXHAUSTIVE_SWEEP_SLOT_LIMIT: u64 = 1 << 12;

fn payload_err(problem: String) -> VectorError {
    VectorError::Payload {
        kind: KIND,
        problem,
    }
}

fn check_err(check: &'static str, problem: String) -> VectorError {
    VectorError::Check {
        kind: KIND,
        check,
        problem,
    }
}

// ---------------------------------------------------------------------------
// payload types
// ---------------------------------------------------------------------------

/// Everything needed to recompute the expectations.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Inputs {
    /// The documented fixed test seed (hex).
    w: String,
    /// The `s_root` derivation label (see [`S_ROOT_LABEL`]).
    s_root_label: String,
    /// The cases, each a content vector plus the openings to prove.
    cases: Vec<CaseInput>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct CaseInput {
    name: String,
    /// The file's byte-domain content, hex; its length **is** `n`.
    content: String,
    openings: Vec<OpeningInput>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct OpeningInput {
    name: String,
    start: u64,
    length: u64,
}

// ---------------------------------------------------------------------------
// executor
// ---------------------------------------------------------------------------

/// Execute a `fine-tree` vector (module docs).
///
/// `inputs`/`expect` arrive from the shared envelope, whose fields (schema,
/// version, NON-SECRET marker, format-version placement) are already checked
/// by the caller.
///
/// # Errors
///
/// Every [`VectorError`] class: a malformed payload, a recomputation that
/// disagrees with the committed document, or a behavioural assertion that
/// the committed values cannot express.
pub fn execute(
    inputs: serde_json::Value,
    expect: serde_json::Value,
    description: String,
) -> Result<VectorSummary, VectorError> {
    let parsed: Inputs =
        serde_json::from_value(inputs).map_err(|e| payload_err(format!("inputs: {e}")))?;

    // Fixture discipline: the document must derive from the documented seed.
    let w_bytes = decode_hex(KIND, "inputs.w", &parsed.w)?;
    let w_array: [u8; 32] = w_bytes
        .try_into()
        .map_err(|_| check_err("w-length", "inputs.w must be exactly 32 bytes".to_owned()))?;
    if w_array != TEST_MASTER_SECRET_W {
        return Err(check_err(
            "w-is-documented-test-seed",
            "inputs.w is not the documented fixed test seed 0x00..0x1f (testdata/README.md)"
                .to_owned(),
        ));
    }
    if parsed.s_root_label != S_ROOT_LABEL {
        return Err(check_err(
            "s-root-label",
            format!(
                "inputs.s_root_label is `{}`, the documented label is `{S_ROOT_LABEL}`",
                parsed.s_root_label
            ),
        ));
    }

    // 1. The whole `expect` object, recomputed and compared as one value.
    let recomputed = build_expect(&parsed)?;
    if recomputed != expect {
        return Err(check_err(
            "document",
            first_difference("expect", &recomputed, &expect),
        ));
    }

    // 2. The assertions a value comparison cannot express.
    let s_root = Seed32::from_bytes(alternate_test_secret(S_ROOT_LABEL.as_bytes()));
    for case in &parsed.cases {
        let content = decode_hex(KIND, "cases[].content", &case.content)?;
        check_case_behaviour(&s_root, case, &content)?;
    }

    // 3. Q5 bit-match: SHA-256 over the serialization of every recomputed
    //    artifact — not a verdict, the bytes themselves. Serializing the
    //    recomputed value (rather than hand-feeding fields) means a future
    //    field is covered the moment it is added.
    let serialized = serde_json::to_vec(&recomputed)
        .map_err(|e| check_err("digest-serialization", e.to_string()))?;
    let mut digest = Sha256::new();
    digest.update(RECOMPUTED_DIGEST_DOMAIN);
    digest.update(KIND.as_bytes());
    digest.update([0x00]);
    digest.update(super::vectors::prefix_len(serialized.len()));
    digest.update(&serialized);

    Ok(VectorSummary {
        kind: KIND,
        description,
        items: parsed.cases.len(),
        recomputed_digest: digest.finalize().into(),
    })
}

/// Recompute the entire `expect` object from `inputs`, through antseal-core's
/// public API (module docs).
///
/// Also the **regenerator**: `tests/fine_tree_vectors.rs` calls this and diffs
/// the result against the committed file, which is the G15-mandated
/// "regenerates and diffs, so drift fails CI" test.
///
/// # Errors
///
/// [`VectorError::Payload`] for a malformed case (bad hex, an opening whose
/// range the file's `n` cannot hold), and [`VectorError::Check`] for a case
/// the fine-tree API itself refuses.
fn build_expect(inputs: &Inputs) -> Result<serde_json::Value, VectorError> {
    let s_root = Seed32::from_bytes(alternate_test_secret(S_ROOT_LABEL.as_bytes()));
    let mut cases = Vec::with_capacity(inputs.cases.len());
    for case in &inputs.cases {
        let content = decode_hex(KIND, "cases[].content", &case.content)?;
        cases.push(build_case(&s_root, case, &content)?);
    }
    Ok(serde_json::json!({
        "s_root": hex(s_root.as_bytes()),
        "cases": cases,
    }))
}

/// Regenerate the whole document (envelope included) from a committed one's
/// `inputs`, so a regenerator can diff bytes-for-value against the file.
///
/// # Errors
///
/// As [`build_expect`], plus [`VectorError::Envelope`] when the supplied
/// document is not a `fine-tree` vector at all.
pub fn regenerate_expect(document: &serde_json::Value) -> Result<serde_json::Value, VectorError> {
    let kind = document.get("kind").and_then(serde_json::Value::as_str);
    if kind != Some(KIND) {
        return Err(VectorError::Envelope(format!(
            "not a `{KIND}` vector (kind is {kind:?})"
        )));
    }
    let inputs = document
        .get("inputs")
        .ok_or_else(|| VectorError::Envelope("document has no `inputs`".to_owned()))?;
    let parsed: Inputs =
        serde_json::from_value(inputs.clone()).map_err(|e| payload_err(format!("inputs: {e}")))?;
    build_expect(&parsed)
}

/// One case's `expect` entry.
fn build_case(
    s_root: &Seed32,
    case: &CaseInput,
    content: &[u8],
) -> Result<serde_json::Value, VectorError> {
    let n = u64::try_from(content.len()).unwrap_or(u64::MAX);
    let Some(depth) = depth_for_leaf_count(n) else {
        // n = 0: an empty file has no fine tree, so there is nothing to pin
        // but its absence (MVP-SPEC.md line 78).
        if !case.openings.is_empty() {
            return Err(check_err(
                "empty-file-has-no-openings",
                format!(
                    "case `{}` is empty (n = 0) but declares openings",
                    case.name
                ),
            ));
        }
        return Ok(serde_json::json!({
            "name": case.name,
            "n": 0,
            "depth": null,
            "slot_count": 0,
            "ggm_nodes": [],
            "salts": [],
            "merkle_nodes": [],
            "fine_root": null,
            "openings": [],
        }));
    };
    let tree = SaltTree::new(s_root, n).ok_or_else(|| {
        check_err(
            "salt-tree",
            format!("case `{}`: no salt tree for n = {n}", case.name),
        )
    })?;

    // Every grid node covering at least one real leaf, in (level, index)
    // order — "all GGM node seeds along used paths".
    let mut ggm_nodes = Vec::new();
    for (level, index) in used_grid_nodes(n, depth) {
        let address = address_of(level, index)?;
        let seed = tree.seed_at(address).map_err(|e| {
            check_err(
                "ggm-seed",
                format!("case `{}`: seed_at({level},{index}): {e}", case.name),
            )
        })?;
        ggm_nodes.push(serde_json::json!({
            "level": level,
            "index": index,
            "seed": hex(seed.as_bytes()),
        }));
    }

    // Every salt — the MSB-first pin.
    let mut salts = Vec::with_capacity(content.len());
    for index in 0..n {
        let salt = tree.salt(index).ok_or_else(|| {
            check_err(
                "salt",
                format!("case `{}`: no salt for leaf {index} of {n}", case.name),
            )
        })?;
        salts.push(serde_json::json!({
            "index": index,
            "salt": hex(salt.as_bytes()),
        }));
    }

    // Every RFC 6962 content-tree node, ordered by subtree width then first
    // leaf (level by level from the leaves up; the last entry is the root).
    let mut spans = Vec::new();
    collect_content_nodes(0, n, &mut spans);
    spans.sort_unstable_by_key(|&(first, end)| (end - first, first));
    let mut merkle_nodes = Vec::with_capacity(spans.len());
    for (first, end) in spans {
        let address = canonical_slot(first, end, n, depth).ok_or_else(|| {
            check_err(
                "canonical-slot",
                format!(
                    "case `{}`: [{first},{end}) is no content-tree node at n = {n}",
                    case.name
                ),
            )
        })?;
        merkle_nodes.push(serde_json::json!({
            "first": first,
            "end": end,
            "level": address.level(),
            "index": address.index(),
            "hash": hex(&subtree_hash(&tree, content, first, end)),
        }));
    }

    let fine_root = rebuild_fine_root(s_root, content).ok_or_else(|| {
        check_err(
            "fine-root",
            format!("case `{}`: rebuild_fine_root returned None", case.name),
        )
    })?;

    let mut openings = Vec::with_capacity(case.openings.len());
    for opening in &case.openings {
        openings.push(build_opening(s_root, case, content, n, opening)?);
    }

    Ok(serde_json::json!({
        "name": case.name,
        "n": n,
        "depth": depth,
        // `u64`: the grid of a `u64`-length file has at most 2^64 slots, which
        // JSON cannot hold — no committed case is anywhere near it, and
        // saturating keeps the executor total on a hostile `n`.
        "slot_count": u64::try_from(tree.slot_count()).unwrap_or(u64::MAX),
        "ggm_nodes": ggm_nodes,
        "salts": salts,
        "merkle_nodes": merkle_nodes,
        "fine_root": hex(fine_root.as_bytes()),
        "openings": openings,
    }))
}

/// One opening's `expect` entry: the full range proof (cover + boundary).
fn build_opening(
    s_root: &Seed32,
    case: &CaseInput,
    content: &[u8],
    leaf_count: u64,
    opening: &OpeningInput,
) -> Result<serde_json::Value, VectorError> {
    let named = |what: &str| format!("case `{}`, opening `{}`: {what}", case.name, opening.name);
    let range = ByteRange::new(opening.start, opening.length);
    let proof = prove_range(s_root, content, range, leaf_count)
        .map_err(|e| check_err("prove-range", named(&format!("prove_range failed: {e}"))))?;
    let cover = minimal_cover(range, leaf_count).map_err(|e| {
        check_err(
            "minimal-cover",
            named(&format!("minimal_cover failed: {e}")),
        )
    })?;

    let start = usize::try_from(opening.start)
        .map_err(|_| payload_err(named("start does not fit this platform's usize")))?;
    let end = start
        .checked_add(
            usize::try_from(opening.length)
                .map_err(|_| payload_err(named("length does not fit this platform's usize")))?,
        )
        .ok_or_else(|| payload_err(named("range end overflows")))?;
    let revealed = content
        .get(start..end)
        .ok_or_else(|| payload_err(named("range is not inside the content")))?;

    Ok(serde_json::json!({
        "name": opening.name,
        "start": opening.start,
        "length": opening.length,
        "revealed_bytes": hex(revealed),
        "releases_s_root": cover.releases_s_root(),
        "cover": proof
            .wire_cover()
            .iter()
            .map(|node| serde_json::json!({
                "level": node.level,
                "index": node.index,
                "seed": hex(node.bytes),
            }))
            .collect::<Vec<_>>(),
        "boundary": proof
            .wire_boundary()
            .iter()
            .map(|node| serde_json::json!({
                "level": node.level,
                "index": node.index,
                "hash": hex(node.bytes),
            }))
            .collect::<Vec<_>>(),
    }))
}

// ---------------------------------------------------------------------------
// the behavioural assertions
// ---------------------------------------------------------------------------

/// The four properties a recomputed-and-compared document cannot state
/// (module docs §"How it is checked").
fn check_case_behaviour(
    s_root: &Seed32,
    case: &CaseInput,
    content: &[u8],
) -> Result<(), VectorError> {
    let n = u64::try_from(content.len()).unwrap_or(u64::MAX);
    let Some(depth) = depth_for_leaf_count(n) else {
        // 4. n = 0 has no tree at all, at every entry point that could offer
        //    one.
        if SaltTree::new(s_root, 0).is_some() {
            return Err(check_err(
                "empty-file-has-no-tree",
                "SaltTree::new accepted n = 0".to_owned(),
            ));
        }
        if rebuild_fine_root(s_root, &[]).is_some() {
            return Err(check_err(
                "empty-file-has-no-tree",
                "rebuild_fine_root produced a root for an empty file".to_owned(),
            ));
        }
        if minimal_cover(ByteRange::new(0, 1), 0).is_ok() {
            return Err(check_err(
                "empty-file-has-no-tree",
                "minimal_cover accepted a range against n = 0".to_owned(),
            ));
        }
        return Ok(());
    };
    let tree = SaltTree::new(s_root, n).ok_or_else(|| {
        check_err(
            "salt-tree",
            format!("case `{}`: no salt tree for n = {n}", case.name),
        )
    })?;

    // 1. MSB-first: walking the same index LSB-first must give a DIFFERENT
    //    salt wherever the reversed path differs. A document generated by an
    //    LSB-first implementation would be internally consistent, so this is
    //    the assertion that actually pins the bit order.
    for index in 0..n {
        if reversed_path_index(index, depth) == index {
            continue; // palindromic path: both orders agree by definition
        }
        let msb_first = tree.salt(index).ok_or_else(|| {
            check_err(
                "salt",
                format!("case `{}`: no salt for leaf {index}", case.name),
            )
        })?;
        if lsb_first_salt(s_root, index, depth).as_bytes() == msb_first.as_bytes() {
            return Err(check_err(
                "msb-first-indexing",
                format!(
                    "case `{}`: leaf {index}'s salt is identical under LSB-first \
                     derivation — the MSB-first rule (MVP-SPEC.md line 96) is not \
                     being exercised",
                    case.name
                ),
            ));
        }
    }

    // 2. Unused slots are never derived: every grid node lying wholly at or
    //    past `n` must be refused, and the used set must be its complement.
    if tree.slot_count() <= u128::from(EXHAUSTIVE_SWEEP_SLOT_LIMIT) {
        for level in 0..=depth {
            for index in 0..(1u64 << level) {
                let address = address_of(level, index)?;
                let used = (index << (depth - level)) < n;
                if used != tree.seed_at(address).is_ok() {
                    return Err(check_err(
                        "unused-slot-refusal",
                        format!(
                            "case `{}`: node ({level},{index}) is {} but seed_at {} it",
                            case.name,
                            if used { "used" } else { "unused" },
                            if used { "refused" } else { "derived" },
                        ),
                    ));
                }
            }
        }
    }

    // 3. Every opening actually opens: the generated proof is run back
    //    through G13's verifier, which is the path a decoded bundle takes.
    let fine_root = rebuild_fine_root(s_root, content).ok_or_else(|| {
        check_err(
            "fine-root",
            format!("case `{}`: rebuild_fine_root returned None", case.name),
        )
    })?;
    for opening in &case.openings {
        let range = ByteRange::new(opening.start, opening.length);
        let proof: RangeProof = prove_range(s_root, content, range, n).map_err(|e| {
            check_err(
                "prove-range",
                format!("case `{}`, opening `{}`: {e}", case.name, opening.name),
            )
        })?;
        let start = usize::try_from(opening.start).unwrap_or(usize::MAX);
        let end = start.saturating_add(usize::try_from(opening.length).unwrap_or(usize::MAX));
        let revealed = content.get(start..end).ok_or_else(|| {
            check_err(
                "opening-range",
                format!(
                    "case `{}`, opening `{}`: range is not inside the content",
                    case.name, opening.name
                ),
            )
        })?;
        proof.verify(revealed, &fine_root).map_err(|e| {
            check_err(
                "opening-verifies",
                format!(
                    "case `{}`, opening `{}`: the committed proof does not verify: {e}",
                    case.name, opening.name
                ),
            )
        })?;
        // The seed-disclosure path is `cover_seeds` and nothing else; running
        // it here asserts the proof's cover is the one that path would ship.
        let cover = minimal_cover(range, n).map_err(|e| {
            check_err(
                "minimal-cover",
                format!("case `{}`, opening `{}`: {e}", case.name, opening.name),
            )
        })?;
        let disclosed: Vec<[u8; 32]> = cover_seeds(s_root, &cover)
            .iter()
            .map(|entry| *entry.payload().as_bytes())
            .collect();
        let in_proof: Vec<[u8; 32]> = proof
            .wire_cover()
            .iter()
            .filter_map(|node| <[u8; 32]>::try_from(node.bytes).ok())
            .collect();
        if disclosed != in_proof {
            return Err(check_err(
                "cover-seeds-agree",
                format!(
                    "case `{}`, opening `{}`: the proof's cover seeds are not the \
                     ones cover_seeds would disclose",
                    case.name, opening.name
                ),
            ));
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/// Every grid node covering at least one real leaf, in `(level, index)` order.
fn used_grid_nodes(leaf_count: u64, depth: u8) -> Vec<(u8, u64)> {
    let mut nodes = Vec::new();
    for level in 0..=depth {
        for index in 0..(1u64 << level) {
            if (index << (depth - level)) < leaf_count {
                nodes.push((level, index));
            }
        }
    }
    nodes
}

/// `NodeAddress::try_new`, reported as a vector error rather than unwrapped.
fn address_of(level: u8, index: u64) -> Result<NodeAddress, VectorError> {
    NodeAddress::try_new(level, index)
        .map_err(|e| check_err("node-address", format!("({level},{index}): {e}")))
}

/// The index whose MSB-first path is the reverse of `index`'s. Equal to
/// `index` exactly when the path is palindromic, which is when the two bit
/// orders cannot be told apart.
fn reversed_path_index(index: u64, depth: u8) -> u64 {
    let mut reversed = 0u64;
    for bit in 0..depth {
        reversed |= ((index >> bit) & 1) << (depth - 1 - bit);
    }
    reversed
}

/// `salt_index` as an LSB-first implementation would compute it — the wrong
/// answer, derived on purpose so the executor can require that it *differs*.
fn lsb_first_salt(s_root: &Seed32, index: u64, depth: u8) -> Salt16 {
    let mut seed = Seed32::from_bytes(*s_root.as_bytes());
    for bit in 0..depth {
        seed = child_seed(
            &seed,
            crate::content::ChildBit::from_bit((index >> bit) & 1 == 1),
        );
    }
    let mut salt = [0u8; Salt16::LEN];
    salt.copy_from_slice(&seed.as_bytes()[..Salt16::LEN]);
    Salt16::from_bytes(salt)
}

/// All content-tree node spans under RFC 6962 promotion, pre-order.
fn collect_content_nodes(first: u64, end: u64, out: &mut Vec<(u64, u64)>) {
    out.push((first, end));
    if end.saturating_sub(first) <= 1 {
        return;
    }
    let split = rfc6962_split(end - first);
    collect_content_nodes(first, first + split, out);
    collect_content_nodes(first + split, end, out);
}

/// The RFC 6962 hash of the subtree over leaves `[first, end)`.
///
/// Uses the crate's single leaf/node preimage sites and its single split
/// definition, so this reference cannot drift from the streaming builder;
/// independence from antseal-core altogether is the Python generator's job.
fn subtree_hash(tree: &SaltTree<'_>, content: &[u8], first: u64, end: u64) -> [u8; 32] {
    if end.saturating_sub(first) <= 1 {
        let salt = tree
            .salt(first)
            .unwrap_or_else(|| Salt16::from_bytes([0; 16]));
        let byte = usize::try_from(first)
            .ok()
            .and_then(|i| content.get(i))
            .copied()
            .unwrap_or(0);
        return leaf_hash(&salt, first, byte);
    }
    let split = rfc6962_split(end - first);
    node_hash(
        &subtree_hash(tree, content, first, first + split),
        &subtree_hash(tree, content, first + split, end),
    )
}

/// Locate the first structural difference between two JSON values, as a
/// path plus the two sides — so a failing vector says *where*, not just
/// "documents differ" over 18 kB of hex.
pub fn first_difference(
    path: &str,
    recomputed: &serde_json::Value,
    committed: &serde_json::Value,
) -> String {
    match (recomputed, committed) {
        (serde_json::Value::Object(a), serde_json::Value::Object(b)) => {
            for (key, value) in a {
                match b.get(key) {
                    None => return format!("{path}.{key}: recomputed has it, the file does not"),
                    Some(other) if other != value => {
                        return first_difference(&format!("{path}.{key}"), value, other);
                    }
                    Some(_) => {}
                }
            }
            for key in b.keys() {
                if !a.contains_key(key) {
                    return format!("{path}.{key}: the file has it, recomputation does not");
                }
            }
            format!("{path}: objects differ but no field does (unreachable)")
        }
        (serde_json::Value::Array(a), serde_json::Value::Array(b)) => {
            if a.len() != b.len() {
                return format!(
                    "{path}: recomputed {} entr(ies), the file pins {}",
                    a.len(),
                    b.len()
                );
            }
            for (i, (value, other)) in a.iter().zip(b).enumerate() {
                if value != other {
                    return first_difference(&format!("{path}[{i}]"), value, other);
                }
            }
            format!("{path}: arrays differ but no element does (unreachable)")
        }
        (a, b) => format!("{path}: recomputed {a}, the file pins {b}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The synthetic seed really is the documented derivation, and really is
    /// not the fixture `W` itself.
    #[test]
    fn s_root_is_the_documented_alternate_test_secret() {
        let s_root = alternate_test_secret(S_ROOT_LABEL.as_bytes());
        assert_ne!(s_root, TEST_MASTER_SECRET_W);
        let mut expected = Sha256::new();
        expected.update(S_ROOT_LABEL.as_bytes());
        expected.update(TEST_MASTER_SECRET_W);
        assert_eq!(s_root, <[u8; 32]>::from(expected.finalize()));
    }

    /// The MSB-first pin's own precondition. A path is *palindromic* when
    /// reading its bits the other way names the same leaf — at `d = 3` those
    /// are 0 (`000`), 2 (`010`), 5 (`101`) and 7 (`111`). Only the others —
    /// 1↔4 and 3↔6 — can tell the two bit orders apart, which is why the
    /// executor's divergence assertion skips the palindromic ones instead of
    /// asserting something false about them.
    #[test]
    fn reversed_path_index_identifies_the_palindromic_leaves() {
        for palindrome in [0u64, 2, 5, 7] {
            assert_eq!(
                reversed_path_index(palindrome, 3),
                palindrome,
                "{palindrome:03b} is its own reverse"
            );
        }
        assert_eq!(reversed_path_index(1, 3), 4);
        assert_eq!(reversed_path_index(4, 3), 1);
        assert_eq!(reversed_path_index(3, 3), 6);
        assert_eq!(reversed_path_index(6, 3), 3);
        assert_eq!(reversed_path_index(0, 0), 0);
    }

    /// The deliberately-wrong LSB-first walk diverges from the shipped
    /// derivation on **exactly** the non-palindromic indices — the executor's
    /// assertion is therefore neither vacuous (it does fire) nor false (it
    /// would not fire on 2 or 5).
    #[test]
    fn lsb_first_salt_diverges_exactly_on_non_palindromic_paths() {
        let s_root = Seed32::from_bytes(alternate_test_secret(S_ROOT_LABEL.as_bytes()));
        let tree = SaltTree::new(&s_root, 6).expect("n = 6");
        for index in 0..6u64 {
            let same = lsb_first_salt(&s_root, index, 3).as_bytes()
                == tree.salt(index).expect("in range").as_bytes();
            assert_eq!(
                same,
                reversed_path_index(index, 3) == index,
                "leaf {index:03b}: the two bit orders agree iff the path is palindromic"
            );
        }
    }

    /// The diff locator names the field, not just "they differ".
    #[test]
    fn first_difference_locates_the_field() {
        let a = serde_json::json!({"cases": [{"n": 6, "fine_root": "aa"}]});
        let b = serde_json::json!({"cases": [{"n": 6, "fine_root": "bb"}]});
        let message = first_difference("expect", &a, &b);
        assert!(message.contains("cases[0].fine_root"), "{message}");
        let short = serde_json::json!({"cases": []});
        assert!(first_difference("expect", &short, &b).contains("entr"));
    }
}
