//! Embeds every committed golden vector into the bit-match harness (Q5).
//!
//! The wasm32 side has no filesystem, so the vectors must travel with the
//! module. This script walks `testdata/vectors/` — **no hardcoded file
//! lists** — and emits a table of `include_bytes!` entries. Dropping a new
//! vector file into the tree is therefore picked up with **zero** harness,
//! runner, or CI changes (Q5 accept: "requires no per-vector wiring"), and
//! `cargo::rerun-if-changed` keeps the embedded table from going stale.
//!
//! The discovery rules mirror `testdata/vectors/README.md` exactly, and — as
//! in the Q4 runner — nothing is ever silently skipped: an unclassifiable
//! file, a non-version directory, or an empty tree fails the **build**.
//! (`crates/antseal-core/tests/vector_runner.rs` owns the same contract at
//! test time; `tests/bitmatch.rs` here cross-checks the two agree.)

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Declared so the deliberate-divergence self-test's `--cfg` is a known
    // condition rather than an `unexpected_cfgs` warning under `-D warnings`.
    println!("cargo::rustc-check-cfg=cfg(antseal_bitmatch_inject_divergence)");

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .unwrap_or_else(|| panic!("{} has no grandparent", manifest_dir.display()))
        .to_path_buf();
    let vectors_root = repo_root.join("testdata").join("vectors");

    // Directory watch: adding, removing, or editing any file under the tree
    // re-runs this script.
    println!("cargo::rerun-if-changed={}", vectors_root.display());
    println!("cargo::rerun-if-changed=build.rs");

    let mut found: Vec<(String, String, PathBuf)> = Vec::new();
    walk_root(&vectors_root, &mut found);
    found.sort();

    if found.is_empty() {
        panic!(
            "{}: zero vector files discovered — discovery is broken or the tree is empty; \
             both must fail loudly (Q4/Q5)",
            vectors_root.display()
        );
    }

    let mut out = String::new();
    out.push_str(
        "// @generated by crates/wasm-bitmatch/build.rs — do not edit.\n\
         /// One committed vector file, embedded at build time.\n\
         #[derive(Debug, Clone, Copy)]\n\
         pub struct EmbeddedVector {\n\
         \x20   /// The `v<n>` directory the file was discovered under.\n\
         \x20   pub format_version: &'static str,\n\
         \x20   /// Repository-relative path, forward slashes on every OS.\n\
         \x20   pub path: &'static str,\n\
         \x20   /// The file's exact bytes.\n\
         \x20   pub bytes: &'static [u8],\n\
         }\n\n\
         /// Every committed vector, sorted by `path`.\n\
         pub static EMBEDDED_VECTORS: &[EmbeddedVector] = &[\n",
    );
    for (rel_path, version, abs_path) in &found {
        println!("cargo::rerun-if-changed={}", abs_path.display());
        let _ = writeln!(
            out,
            "    EmbeddedVector {{ format_version: {version:?}, path: {rel_path:?}, \
             bytes: include_bytes!({:?}) }},",
            abs_path.display().to_string()
        );
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"))
        .join("embedded_vectors.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

/// Directly under `vectors/`: only `README.md` and `v<integer>/`.
fn walk_root(root: &Path, found: &mut Vec<(String, String, PathBuf)>) {
    for entry in sorted_entries(root) {
        let name = file_name(&entry);
        if entry.is_dir() {
            assert!(
                is_version_dirname(&name),
                "{}: directories under vectors/ must be format-version directories (`v<integer>`); \
                 found `{name}` (testdata/vectors/README.md)",
                entry.display()
            );
            walk_version_dir(&entry, &name, found);
        } else {
            assert!(
                name == "README.md",
                "{}: only README.md and v<integer>/ directories may sit directly under vectors/ \
                 (testdata/vectors/README.md)",
                entry.display()
            );
        }
    }
}

/// Inside a version directory: `*.json` are vectors, a fixed set of names
/// are documented auxiliaries, anything else fails the build.
fn walk_version_dir(dir: &Path, version: &str, found: &mut Vec<(String, String, PathBuf)>) {
    for entry in sorted_entries(dir) {
        if entry.is_dir() {
            walk_version_dir(&entry, version, found);
            continue;
        }
        let name = file_name(&entry);
        // F10's per-version roster is an auxiliary, not a vector: it carries
        // no `kind`/`inputs`/`expect`, so embedding it would hand the bit-match
        // executor a file it cannot run.
        if name == "INDEX.json" {
            continue;
        }
        if name.ends_with(".json") {
            found.push((repo_relative(&entry), version.to_owned(), entry));
        } else {
            assert!(
                name == "README.md" || name == "FROZEN.sha256" || name.ends_with(".py"),
                "{}: unclassifiable file under vectors/{version}/ — every file must be a vector \
                 (*.json) or a documented auxiliary (README.md, *.py, FROZEN.sha256, INDEX.json); \
                 nothing is silently skipped (Q4/Q5)",
                entry.display()
            );
        }
    }
}

fn sorted_entries(dir: &Path) -> Vec<PathBuf> {
    let read = fs::read_dir(dir).unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()));
    let mut entries: Vec<PathBuf> = read
        .map(|entry| {
            entry
                .unwrap_or_else(|e| panic!("dir entry error under {}: {e}", dir.display()))
                .path()
        })
        .collect();
    entries.sort();
    entries
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .and_then(|n| n.to_str())
        .map(str::to_owned)
        .unwrap_or_else(|| panic!("{}: non-UTF-8 file name in testdata", path.display()))
}

fn is_version_dirname(name: &str) -> bool {
    name.strip_prefix('v')
        .is_some_and(|digits| !digits.is_empty() && digits.bytes().all(|b| b.is_ascii_digit()))
}

/// `testdata/vectors/...` with forward slashes, so the transcript is
/// identical on Windows checkouts too (the `cross-os-*` lanes care).
fn repo_relative(path: &Path) -> String {
    let text = path.display().to_string().replace('\\', "/");
    match text.find("testdata/vectors/") {
        Some(at) => text[at..].to_owned(),
        None => panic!("{text}: vector path is not under testdata/vectors/"),
    }
}
