#!/usr/bin/env python3
"""Derive the committed ML-DSA-65 ACVP subsets from NIST's upstream files.

Decision D31 makes NIST ACVP the **T0** vehicle for ML-DSA-65 (vehicle
register rows 12 and 13). T0 means the expected values originate outside this
project *and* outside its language ecosystem — NIST's files are generated by
NIST's own reference implementation from NIST's own text — which is the only
tier that catches a shared misreading of FIPS 204. That matters more here than
anywhere else in the register: FIPS 204's `ctx` / `Sign_internal` split is
exactly the kind of 2024-standard subtlety two Rust crates could misread
together.

Upstream is 14.4 MB across three files. This script produces the ~2 MB
ML-DSA-65 subset the harness actually drives, and exists so the committed
bytes are a **reproducible derivative rather than a blob of trust**: fetch the
upstream file, check its SHA-256 against PROVENANCE.md, re-run with `--check`,
and diff.

## The filter

Per D31 section 4c Branch A, with one correction the decision could not have
known without running the probe:

- `parameterSet == "ML-DSA-65"` — antseal's only parameter set.
- **drop `preHash == "preHash"`** — HashML-DSA, which antseal does not
  implement. D31 wrote this as `preHash == "pure"`, but the probe shows the
  *internal*-interface groups carry `preHash == "none"`, not `"pure"`. Taken
  literally, D31's filter would have dropped every internal group while its
  prose says to keep "both signatureInterface values". Excluding `"preHash"`
  is what the decision meant and what the harness needs.
- **drop `externalMu == True`** — those groups supply a precomputed `mu`
  instead of a message. `ml-dsa` can drive them (`sign_mu_deterministic`,
  `verify_mu`) but they test a surface antseal does not use.
- keep both `signatureInterface` values and both `deterministic` values.

**No case is dropped**: all 115 ML-DSA-65 cases for the interfaces antseal
uses are committed. Complete coverage of our parameter set is a cleaner claim
than any sampling rule, and this is freeze evidence retained forever.

Two fields *are* dropped, and only because they are provably unusable by the
harness (see DROPPED_FIELDS below). Verbatim cases would have been better for
auditability, but the subset came to 2.7 MB against a 6.8 MB tree — three
times D31 section 5's estimate, which was computed from the smaller 2024 file
before the probe found the richer 2026 one. Dropping the two redundant
megabyte-scale fields is the smallest change that fixes the disproportion:

- `sigGen[].pk` — sigGen signs with `sk` and compares signature bytes. The
  public key is derivable (`ExpandedSigningKey::verifying_key`), and the
  seed -> (pk, sk) map is exactly what the keyGen file already validates.
- `sigVer[].sk` — verification never touches a signing key.

Every other field is upstream's, unmodified.

## Usage

    python3 filter_acvp.py --source-dir /path/to/gen-val/json-files
    python3 filter_acvp.py --source-dir /path/to/gen-val/json-files --check

`--source-dir` accepts the upstream repository layout
(`ML-DSA-sigGen-FIPS204/internalProjection.json`) or a flat directory of files
named `ML-DSA-<mode>-FIPS204.internalProjection.json`.

This script is **not** run by CI: it needs the upstream files, which means the
network. The committed subsets are what the always-on lane consumes, through
`crates/antseal-core/tests/acvp_ml_dsa.rs`.
"""

import argparse
import hashlib
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent

MODES = ("keyGen", "sigGen", "sigVer")
PARAMETER_SET = "ML-DSA-65"

# Per-mode fields dropped from every test case, and only these. Both are
# provably unusable by the harness; see the module docstring for why they are
# dropped at all rather than keeping cases verbatim.
DROPPED_FIELDS = {
    "keyGen": (),
    "sigGen": ("pk",),
    "sigVer": ("sk",),
}


def source_path(source_dir: pathlib.Path, mode: str) -> "pathlib.Path | None":
    """Locate one upstream file under either supported layout."""
    candidates = (
        source_dir / f"ML-DSA-{mode}-FIPS204" / "internalProjection.json",
        source_dir / f"ML-DSA-{mode}-FIPS204.internalProjection.json",
    )
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def keep_group(group: dict) -> bool:
    """The documented filter, as one predicate."""
    if group.get("parameterSet") != PARAMETER_SET:
        return False
    if group.get("preHash") == "preHash":
        return False
    if group.get("externalMu") is True:
        return False
    return True


def filter_document(doc: dict, mode: str) -> dict:
    """Project one upstream document onto its ML-DSA-65 groups."""
    dropped = DROPPED_FIELDS[mode]
    groups = []
    for group in doc.get("testGroups", []):
        if not keep_group(group):
            continue
        group = dict(group)
        group["tests"] = [
            {k: v for k, v in case.items() if k not in dropped}
            for case in group.get("tests", [])
        ]
        groups.append(group)
    if not groups:
        raise SystemExit(
            "filter produced zero test groups — the upstream file's shape changed; "
            "re-run the D31 section 4c acquisition probe before touching this filter"
        )
    return {
        "vsId": doc.get("vsId"),
        "algorithm": doc.get("algorithm"),
        "mode": doc.get("mode"),
        "revision": doc.get("revision"),
        "isSample": doc.get("isSample"),
        "testGroups": groups,
    }


def render(doc: dict) -> str:
    return json.dumps(doc, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Derive the ML-DSA-65 ACVP subsets.")
    parser.add_argument(
        "--source-dir",
        required=True,
        type=pathlib.Path,
        help="directory holding the upstream internalProjection.json files",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare against the committed subsets instead of writing them",
    )
    args = parser.parse_args()

    status = 0
    for mode in MODES:
        upstream = source_path(args.source_dir, mode)
        if upstream is None:
            print(
                f"error: no upstream file for {mode} under {args.source_dir} "
                "(see PROVENANCE.md for the URLs)",
                file=sys.stderr,
            )
            return 2
        raw = upstream.read_bytes()
        digest = hashlib.sha256(raw).hexdigest()
        produced = render(filter_document(json.loads(raw), mode))
        target = HERE / f"ml-dsa-65-{mode}.json"

        cases = sum(
            len(group.get("tests", []))
            for group in json.loads(produced)["testGroups"]
        )
        if args.check:
            if not target.exists():
                print(f"FAIL  {target.name}: committed subset is missing", file=sys.stderr)
                status = 1
                continue
            if target.read_text(encoding="utf-8") == produced:
                print(f"OK    {target.name} re-derives ({cases} cases, upstream {digest[:16]}…)")
            else:
                print(
                    f"FAIL  {target.name}: re-derived bytes differ from the committed "
                    "subset — a different upstream pin, or the filter changed",
                    file=sys.stderr,
                )
                status = 1
            continue

        target.write_text(produced, encoding="utf-8")
        print(
            f"wrote {target.name}: {cases} ML-DSA-65 cases, "
            f"{len(produced.encode('utf-8'))} bytes (upstream sha256 {digest})"
        )
    return status


if __name__ == "__main__":
    raise SystemExit(main())
