//! NIST ACVP replay for ML-DSA-65 — the **T0** external oracle (D31 rows 12/13).
//!
//! Decision D31 grades every cross-check vehicle into three tiers, and the
//! grading is the point:
//!
//! - **T0** — an external oracle, values originating outside this project *and*
//!   outside its language ecosystem. The only tier that catches a **shared
//!   misreading of the specification**.
//! - **T1** — an independent re-implementation. Catches implementation and
//!   transcription bugs; blind to a shared misreading.
//! - **T2** — two implementations inside one ecosystem. Blind to both.
//!
//! NIST's ACVP files are generated by NIST's own reference implementation from
//! NIST's own text, so this file sits at T0 — and ML-DSA therefore ends up
//! *better* covered than the surfaces with hand-written Python references, not
//! worse, which was the opposite of what Q11's task text assumed.
//!
//! **This file is the independent cross-check for ML-DSA-65.** Its neighbour
//! `mldsa_fallback_equivalence.rs` compares `ml-dsa` against `fips204`; that is
//! T2, it is evidence for D14's fallback claim only, and it never counts toward
//! the independence claim. Two checks, two purposes, neither substituting for
//! the other (D31 §4a).
//!
//! # What it drives
//!
//! The call shapes here mirror `antseal_core::crypto::sig_mldsa` exactly, so the
//! replay validates *antseal's own call path* rather than a parallel one:
//!
//! | ACVP mode | this harness | `sig_mldsa` |
//! | --- | --- | --- |
//! | keyGen | `SigningKey::<MlDsa65>::from_seed` | `signing_key()` |
//! | sigGen, external | `ExpandedSigningKey::sign_deterministic(M, ctx)` | `sign_with_context()` |
//! | sigVer, external | `VerifyingKey::verify_with_context(M, ctx, &sig)` | `verify_with_context()` |
//! | sigVer, canonical gate | `Signature::try_from(&[u8])` | same, mapped to `NonCanonicalSignature` |
//!
//! The internal-interface groups additionally drive `sign_internal`, which is
//! not an antseal call path but is what the external interface is *defined in
//! terms of*, and is where the `ctx` absorption gets checked (below).
//!
//! # Row 13 — `ctx` absorption, and why it is T0 here
//!
//! FIPS 204 Algorithm 2 builds `M′ = 0x00 ‖ len(ctx) ‖ ctx ‖ M` and hands it to
//! `Sign_internal`. D31 §4c planned for the possibility (Branch B) that ACVP
//! carried no external-interface groups, in which case row 13 would have fallen
//! back to asserting that hand-derivation against our own internal calls — T1,
//! self-consistent, and unable to notice if we had read Algorithm 2 wrong.
//!
//! The acquisition probe found **Branch A**: external groups with a populated
//! `context` exist (see `testdata/acvp/PROVENANCE.md`). So this file does both,
//! and the second is what makes row 13 genuinely T0:
//!
//! 1. `sign_deterministic(M, ctx)` reproduces NIST's signature bytes — the
//!    crate's own Algorithm 2 is right.
//! 2. the *hand-derived* `M′` fed to `sign_internal` reproduces the same NIST
//!    bytes — **our reading** of Algorithm 2 is right, checked against NIST
//!    rather than against ourselves.
//!
//! # Not vacuous
//!
//! Every test asserts its own case count against a constant. A truncated or
//! mis-filtered fixture must fail loudly; a replay suite that silently runs
//! zero cases is worse than no suite, because it reports success.
//!
//! # Scope
//!
//! `wasm32` is out of scope — this is fixture replay, and the native/WASM
//! bit-match is Q5's job (D31 §9 step 5). No network: the subsets are
//! committed, so this runs in the ordinary `test` lane.

use std::fs;
use std::path::PathBuf;

use ml_dsa::{
    B32, EncodedVerifyingKey, ExpandedSigningKey, Keypair, MlDsa65, Signature, SigningKey,
    VerifyingKey,
};
use serde_json::Value;

/// Where the committed subsets live. Workspace-relative through the manifest
/// dir, so it holds on every OS and checkout location.
const ACVP_ROOT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../testdata/acvp");

/// Case counts, pinned so a truncated fixture fails instead of passing
/// vacuously. These are the full ML-DSA-65 subsets — see
/// `testdata/acvp/PROVENANCE.md` for the filter that produced them.
const KEYGEN_CASES: usize = 25;
const SIGGEN_INTERNAL_CASES: usize = 30;
const SIGGEN_EXTERNAL_CASES: usize = 30;
const SIGVER_INTERNAL_CASES: usize = 15;
const SIGVER_EXTERNAL_CASES: usize = 15;

/// FIPS 204 Table 2 sizes for ML-DSA-65.
const PUBLIC_KEY_LEN: usize = 1952;
const EXPANDED_SIGNING_KEY_LEN: usize = 4032;
const SIGNATURE_LEN: usize = 3309;

// ── fixture loading ────────────────────────────────────────────────────────

fn load(mode: &str) -> Value {
    let path = PathBuf::from(ACVP_ROOT).join(format!("ml-dsa-65-{mode}.json"));
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read the committed ACVP subset {path:?}: {e}"));
    serde_json::from_str(&raw).unwrap_or_else(|e| {
        panic!("{path:?} is not valid JSON: {e} (re-derive with filter_acvp.py)")
    })
}

/// Every test group in one file, as `(group, cases)`.
fn groups(doc: &Value) -> Vec<&Value> {
    doc["testGroups"]
        .as_array()
        .expect("ACVP documents always carry a testGroups array")
        .iter()
        .collect()
}

fn is_external(group: &Value) -> bool {
    group["signatureInterface"] == *"external"
}

fn is_deterministic(group: &Value) -> bool {
    group["deterministic"] == Value::Bool(true)
}

fn cases(group: &Value) -> &Vec<Value> {
    group["tests"]
        .as_array()
        .expect("every group carries tests")
}

/// Decode an ACVP hex string. NIST emits uppercase; accept either.
fn hex(case: &Value, field: &str) -> Vec<u8> {
    let text = case[field]
        .as_str()
        .unwrap_or_else(|| panic!("case {} has no string field `{field}`", case["tcId"]));
    decode_hex(text)
        .unwrap_or_else(|| panic!("case {} field `{field}` is not hex: {text:?}", case["tcId"]))
}

/// An optional hex field — ACVP omits `context` on the internal interface and
/// `rnd` on deterministic groups.
fn hex_opt(case: &Value, field: &str) -> Option<Vec<u8>> {
    case.get(field)
        .and_then(Value::as_str)
        .map(|text| decode_hex(text).expect("ACVP hex field"))
}

fn decode_hex(text: &str) -> Option<Vec<u8>> {
    if !text.len().is_multiple_of(2) {
        return None;
    }
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).ok())
        .collect()
}

// ── crate adapters (the exact shapes `sig_mldsa` uses) ─────────────────────

fn verifying_key(pk: &[u8]) -> VerifyingKey<MlDsa65> {
    let encoded = <&EncodedVerifyingKey<MlDsa65>>::try_from(pk)
        .expect("ACVP ML-DSA-65 public keys are exactly 1952 bytes");
    VerifyingKey::<MlDsa65>::decode(encoded)
}

/// Decode ACVP's 4032-byte `sk` into an expanded signing key.
///
/// `from_expanded` is deprecated upstream in favour of `from_seed`, and for
/// production that is right — antseal never decodes an expanded key, it always
/// derives ξ from `W`. But ACVP's sigGen cases supply `sk` and no seed, so
/// replaying them requires Algorithm 25 `skDecode`. The deprecation warns about
/// panics on malformed input; these are NIST's own well-formed keys.
#[expect(deprecated, reason = "ACVP sigGen supplies sk bytes, never a seed")]
fn expanded_signing_key(sk: &[u8]) -> ExpandedSigningKey<MlDsa65> {
    let encoded = sk
        .try_into()
        .expect("ACVP ML-DSA-65 signing keys are exactly 4032 bytes");
    ExpandedSigningKey::<MlDsa65>::from_expanded(encoded)
}

/// FIPS 204 Algorithm 2's message prefix, derived by hand from the standard's
/// text: `M′ = 0x00 ‖ len(ctx) ‖ ctx ‖ M`.
///
/// The `0x00` is the domain separator distinguishing pure ML-DSA from
/// HashML-DSA; `len(ctx)` is a single byte, which is why FIPS 204 caps `ctx` at
/// 255. Checking *this* against NIST's external-interface answers is what
/// promotes row 13 from "the crate agrees with itself" to T0.
fn algorithm_2_prefix(ctx: &[u8]) -> Vec<u8> {
    assert!(ctx.len() <= 255, "FIPS 204 caps ctx at 255 bytes");
    let mut prefix = Vec::with_capacity(2 + ctx.len());
    prefix.push(0x00);
    prefix.push(u8::try_from(ctx.len()).expect("checked above"));
    prefix.extend_from_slice(ctx);
    prefix
}

// ── keyGen (row 12) ────────────────────────────────────────────────────────

/// ACVP keyGen: seed → (pk, sk), against `SigningKey::<MlDsa65>::from_seed`,
/// the call `sig_mldsa::signing_key` makes.
#[test]
#[expect(
    deprecated,
    reason = "ACVP pins the encoded expanded key, not the seed"
)]
fn acvp_ml_dsa65_keygen() {
    let doc = load("keyGen");
    let mut checked = 0usize;

    for group in groups(&doc) {
        for case in cases(group) {
            let seed = hex(case, "seed");
            let want_pk = hex(case, "pk");
            let want_sk = hex(case, "sk");
            assert_eq!(want_pk.len(), PUBLIC_KEY_LEN, "case {}", case["tcId"]);
            assert_eq!(
                want_sk.len(),
                EXPANDED_SIGNING_KEY_LEN,
                "case {}",
                case["tcId"]
            );

            let seed = <&B32>::try_from(seed.as_slice()).expect("ACVP seeds are 32 bytes");
            let key = SigningKey::<MlDsa65>::from_seed(seed);

            assert_eq!(
                key.verifying_key().encode().as_slice(),
                want_pk.as_slice(),
                "ACVP keyGen tcId {}: ml-dsa public key disagrees with NIST",
                case["tcId"]
            );
            assert_eq!(
                key.expanded_key().to_expanded().as_slice(),
                want_sk.as_slice(),
                "ACVP keyGen tcId {}: ml-dsa signing key disagrees with NIST",
                case["tcId"]
            );
            checked += 1;
        }
    }

    assert_eq!(
        checked, KEYGEN_CASES,
        "ACVP keyGen ran {checked} cases, expected {KEYGEN_CASES} — the committed \
         subset is truncated or mis-filtered, and a replay suite that runs no cases \
         reports success while proving nothing"
    );
}

// ── sigGen, internal interface (row 12) ────────────────────────────────────

/// ACVP sigGen over `Sign_internal` (Algorithm 7), both deterministic
/// (`rnd = 0³²`, D15's mode) and randomized (ACVP supplies `rnd`).
#[test]
fn acvp_ml_dsa65_siggen_internal() {
    let doc = load("sigGen");
    let mut checked = 0usize;

    for group in groups(&doc).into_iter().filter(|g| !is_external(g)) {
        for case in cases(group) {
            let key = expanded_signing_key(&hex(case, "sk"));
            let message = hex(case, "message");
            let want = hex(case, "signature");
            assert_eq!(want.len(), SIGNATURE_LEN, "case {}", case["tcId"]);

            // Deterministic groups carry no `rnd`; FIPS 204's deterministic
            // variant substitutes 0³², which is exactly D15's mode.
            let rnd = hex_opt(case, "rnd").unwrap_or_else(|| vec![0u8; 32]);
            assert_eq!(
                is_deterministic(group),
                case.get("rnd").is_none(),
                "ACVP sigGen tcId {}: deterministic groups must be exactly the \
                 ones without an `rnd` field",
                case["tcId"]
            );
            let rnd = <&B32>::try_from(rnd.as_slice()).expect("rnd is 32 bytes");

            let signature = key.sign_internal(&[&message], rnd);
            assert_eq!(
                signature.encode().as_slice(),
                want.as_slice(),
                "ACVP sigGen (internal) tcId {}: ml-dsa signature disagrees with NIST",
                case["tcId"]
            );
            checked += 1;
        }
    }

    assert_eq!(
        checked, SIGGEN_INTERNAL_CASES,
        "ACVP sigGen (internal) ran {checked} cases, expected {SIGGEN_INTERNAL_CASES}"
    );
}

// ── sigGen, external interface (row 13 — the ctx absorption) ───────────────

/// ACVP sigGen over the **external** interface: `ML-DSA.Sign` (Algorithm 2)
/// with a real `ctx`. This is antseal's actual call.
///
/// Two independent assertions per deterministic case, per the module docs:
/// the crate's `sign_deterministic`, and our hand-derived `M′` through
/// `sign_internal`. Randomized cases can only take the second route —
/// `sign_randomized` wants an RNG, not a fixed `rnd` — which is no loss,
/// because the second route is the stronger of the two.
#[test]
fn acvp_ml_dsa65_siggen_external_ctx_absorption() {
    let doc = load("sigGen");
    let mut checked = 0usize;
    let mut via_sign_deterministic = 0usize;
    let mut widest_ctx = 0usize;

    for group in groups(&doc).into_iter().filter(|g| is_external(g)) {
        for case in cases(group) {
            let key = expanded_signing_key(&hex(case, "sk"));
            let message = hex(case, "message");
            let ctx = hex(case, "context");
            let want = hex(case, "signature");
            widest_ctx = widest_ctx.max(ctx.len());

            // (1) Our reading of FIPS 204 Algorithm 2, checked against NIST.
            //     This is the assertion that makes row 13 T0 rather than a
            //     self-consistency check.
            let rnd = hex_opt(case, "rnd").unwrap_or_else(|| vec![0u8; 32]);
            let rnd = <&B32>::try_from(rnd.as_slice()).expect("rnd is 32 bytes");
            let prefix = algorithm_2_prefix(&ctx);
            let derived = key.sign_internal(&[&prefix, &message], rnd);
            assert_eq!(
                derived.encode().as_slice(),
                want.as_slice(),
                "ACVP sigGen (external) tcId {}: the hand-derived FIPS 204 \
                 Algorithm 2 pre-image M' = 0x00 || len(ctx) || ctx || M does not \
                 reproduce NIST's signature (ctx = {} bytes)",
                case["tcId"],
                ctx.len()
            );

            // (2) The crate's own Algorithm 2, i.e. antseal's exact call.
            //     Only reachable for deterministic cases.
            if is_deterministic(group) {
                let signature = key
                    .sign_deterministic(&message, &ctx)
                    .expect("ACVP contexts are at most 255 bytes");
                assert_eq!(
                    signature.encode().as_slice(),
                    want.as_slice(),
                    "ACVP sigGen (external) tcId {}: sign_deterministic disagrees \
                     with NIST",
                    case["tcId"]
                );
                via_sign_deterministic += 1;
            }
            checked += 1;
        }
    }

    assert_eq!(
        checked, SIGGEN_EXTERNAL_CASES,
        "ACVP sigGen (external) ran {checked} cases, expected {SIGGEN_EXTERNAL_CASES}"
    );
    assert_eq!(
        via_sign_deterministic,
        SIGGEN_EXTERNAL_CASES / 2,
        "half the external cases are the deterministic groups; \
         {via_sign_deterministic} took the sign_deterministic route"
    );
    // The ctx=255 boundary is the one FIPS 204's single length byte makes
    // interesting. If the fixture ever loses it, say so rather than passing.
    assert_eq!(
        widest_ctx, 255,
        "the external sigGen cases should reach the 255-byte ctx boundary; \
         widest seen was {widest_ctx}"
    );
}

// ── sigVer (row 12, and D14's canonical-rejection claim) ───────────────────

/// Replay one sigVer group, returning `(checked, rejected_at_decode)`.
///
/// `testPassed: false` cases must be refused, and antseal has two refusal
/// paths: `Signature::decode` returning `None` (non-canonical encoding —
/// `sig_mldsa` maps this to `CryptoError::NonCanonicalSignature`) and
/// verification returning `false` (`SignatureInvalid`). Either is a correct
/// rejection; the split is recorded because D14 claims canonical rejection is
/// *complete* at `Signature::decode`, and this is where that claim meets NIST's
/// own negative cases.
fn replay_sigver(group: &Value, external: bool) -> (usize, usize) {
    let mut checked = 0usize;
    let mut rejected_at_decode = 0usize;

    for case in cases(group) {
        let vk = verifying_key(&hex(case, "pk"));
        let message = hex(case, "message");
        let signature_bytes = hex(case, "signature");
        let expected = case["testPassed"]
            .as_bool()
            .expect("every sigVer case carries testPassed");
        let reason = case["reason"].as_str().unwrap_or("<none>");

        let accepted = match Signature::<MlDsa65>::try_from(signature_bytes.as_slice()) {
            Err(_) => {
                rejected_at_decode += 1;
                false
            }
            Ok(signature) => {
                if external {
                    let ctx = hex(case, "context");
                    vk.verify_with_context(&message, &ctx, &signature)
                } else {
                    vk.verify_internal(&message, &signature)
                }
            }
        };

        assert_eq!(
            accepted,
            expected,
            "ACVP sigVer tcId {}: ml-dsa {} where NIST says {} (reason: {reason})",
            case["tcId"],
            if accepted { "accepted" } else { "rejected" },
            if expected { "accept" } else { "reject" },
        );
        checked += 1;
    }

    (checked, rejected_at_decode)
}

/// ACVP sigVer over `Verify_internal`, including NIST's negative cases.
#[test]
fn acvp_ml_dsa65_sigver_internal() {
    let doc = load("sigVer");
    let mut checked = 0usize;

    for group in groups(&doc).into_iter().filter(|g| !is_external(g)) {
        let (n, _) = replay_sigver(group, false);
        checked += n;
    }

    assert_eq!(
        checked, SIGVER_INTERNAL_CASES,
        "ACVP sigVer (internal) ran {checked} cases, expected {SIGVER_INTERNAL_CASES}"
    );
}

/// ACVP sigVer over `ML-DSA.Verify` with a real `ctx` — antseal's actual
/// verification call, negatives included.
#[test]
fn acvp_ml_dsa65_sigver_external_ctx_absorption() {
    let doc = load("sigVer");
    let mut checked = 0usize;

    for group in groups(&doc).into_iter().filter(|g| is_external(g)) {
        let (n, _) = replay_sigver(group, true);
        checked += n;
    }

    assert_eq!(
        checked, SIGVER_EXTERNAL_CASES,
        "ACVP sigVer (external) ran {checked} cases, expected {SIGVER_EXTERNAL_CASES}"
    );
}

/// The negative cases exist, cover every failure reason NIST ships, and are
/// genuinely negative.
///
/// D31 §11 item 6 asks for a *proof of failure*: a suite never observed
/// failing proves nothing. The sigVer negatives are that proof standing
/// permanently in the suite — if `verify_with_context` were stubbed to return
/// `true`, `acvp_ml_dsa65_sigver_*` would go red on these cases. This test
/// guards the guard: it fails if the negatives were ever filtered away.
#[test]
fn acvp_ml_dsa65_sigver_negatives_are_present_and_complete() {
    let doc = load("sigVer");
    let mut reasons: Vec<String> = Vec::new();
    let mut negatives = 0usize;
    let mut positives = 0usize;

    for group in groups(&doc) {
        for case in cases(group) {
            let passed = case["testPassed"].as_bool().expect("testPassed");
            let reason = case["reason"].as_str().unwrap_or("<none>").to_owned();
            if passed {
                positives += 1;
            } else {
                negatives += 1;
                if !reasons.contains(&reason) {
                    reasons.push(reason);
                }
            }
        }
    }

    reasons.sort();
    assert_eq!(
        reasons,
        vec![
            "modified message".to_owned(),
            "modified signature - commitment".to_owned(),
            "modified signature - hint".to_owned(),
            "modified signature - z".to_owned(),
        ],
        "NIST's sigVer failure reasons changed or were filtered away; the \
         negative cases are where D14's `canonical rejection is complete at \
         Signature::decode` claim gets its external confirmation"
    );
    assert_eq!(negatives, 24, "expected 24 negative sigVer cases");
    assert_eq!(positives, 6, "expected 6 positive sigVer cases");
}
