//! F16 — property tests for the codec: round-trip, determinism, and
//! canonicality (MVP-SPEC.md line 167 "property tests"; line 73 the
//! deterministic-CBOR profile).
//!
//! Five properties, over arbitrary **schema-valid** manifests generated by
//! `test_util::strategies` and bounded by F11's caps:
//!
//! 1. `encode -> strict-decode` round-trips to an equal value;
//! 2. `encode` is deterministic — repeated encodes are byte-identical;
//! 3. encoder output always passes the strict decoder;
//! 4. `decode -> re-encode` reproduces the input bytes exactly, for canonical
//!    input (spec line 74: verifiers never re-encode, so this is a statement
//!    about the *encoder*, not a licence to normalize);
//! 5. every generated non-canonical mutation fails with the **correct error
//!    class**, and nothing ever panics.
//!
//! # The cap profile
//!
//! Generation runs against `strategies::GenCaps::PROFILE`, the test-only
//! reduced-cap profile decision D10 §5 flagged for this task: generating at
//! 65 536 units or 256 MiB is not viable in a property corpus. The real caps
//! are covered by F11's dedicated at-cap/cap+1 matrix in
//! `tests/parser_caps.rs`. `caps_profile_stays_inside_the_production_caps`
//! below is the guard that keeps the two consistent — the profile may only
//! ever be *smaller*, never larger, or the round-trip properties would pass
//! vacuously on rejections.
//!
//! # Conventions (Q3)
//!
//! Fixed per-block seeds; `strategies::integration_test_config`, because a
//! suite in `tests/` has no `lib.rs` ancestor and proptest's default
//! persistence would silently store nothing — a CI failure would then be
//! unreproducible locally. Note also that `PROPTEST_CASES` **overrides** a
//! hardcoded `cases` (the `proptest!` macro re-applies `contextualize_config`
//! after the literal is built); no property here declares a floor, so nothing
//! in this file depends on that either way.

use std::collections::BTreeSet;
use std::sync::Mutex;

use antseal_core::bundle::{BundleV1, encode_bundle};
use antseal_core::codec::{DecodeError, check_canonical};
use antseal_core::manifest::{Manifest, ManifestError, encode_body, encode_envelope};
use antseal_core::test_util::proptest::prelude::*;
use antseal_core::test_util::strategies::{self, GenCaps, MutationKind};

const CAPS: GenCaps = GenCaps::PROFILE;
const REGRESSIONS: &str = "proptest-regressions/codec_properties.txt";

/// Which mutation classes the corpus actually reached. A `BTreeSet` behind a
/// `Mutex` rather than an atomic bitset because the assertion wants to *name*
/// the classes it missed, and proptest runs cases on one thread per block.
static COVERED: Mutex<BTreeSet<MutationKind>> = Mutex::new(BTreeSet::new());

fn record(kind: MutationKind) {
    if let Ok(mut set) = COVERED.lock() {
        set.insert(kind);
    }
}

/// The decode error a manifest rejection carries, whichever layer raised it.
fn code_of(err: &ManifestError) -> &'static str {
    err.code()
}

// ───────────────────────────────────────────────────────────────────────
// The cap-profile guard
// ───────────────────────────────────────────────────────────────────────

/// The reduced-cap profile must sit at or under every production cap.
///
/// Not a property but a precondition of all of them: a profile *above* an
/// enforced cap would generate inputs the decoder refuses, and every
/// round-trip property below would then pass vacuously on the rejection
/// instead of exercising the codec.
#[test]
fn caps_profile_stays_inside_the_production_caps() {
    CAPS.assert_within_production_caps();
}

// ───────────────────────────────────────────────────────────────────────
// Properties 1–4: round-trip, determinism, encoder/decoder agreement
// ───────────────────────────────────────────────────────────────────────

proptest! {
    #![proptest_config(strategies::integration_test_config(0x5EED_F160, REGRESSIONS))]

    /// **Property 1 + 3.** A schema-valid body encodes, strict-decodes, and
    /// comes back equal. Property 3 (encoder output always passes the strict
    /// decoder) is the same statement's first half, asserted separately so a
    /// failure says which half broke.
    #[test]
    fn body_round_trips_through_the_strict_decoder(
        body in strategies::arb_manifest_body(CAPS)
    ) {
        let expected = body.clone();
        let bytes = encode_body(body).expect("a schema-valid body encodes");

        // Property 3: the generic canonicality pass accepts encoder output.
        prop_assert_eq!(check_canonical(&bytes), Ok(()));

        // Property 1: the typed pass returns an equal value.
        let decoded = antseal_core::manifest::ManifestBodyV1::decode(&bytes)
            .expect("encoder output must strict-decode");
        prop_assert_eq!(decoded, expected);
    }

    /// **Property 2.** Encoding is a function of the value alone: the same
    /// logical body always produces identical bytes. This is what makes
    /// `work_id = SHA-256(manifest body)` well defined at all.
    #[test]
    fn encoding_is_deterministic(body in strategies::arb_manifest_body(CAPS)) {
        let once = encode_body(body.clone()).expect("encodes");
        let twice = encode_body(body.clone()).expect("encodes");
        let thrice = encode_body(body).expect("encodes");
        prop_assert_eq!(&once, &twice);
        prop_assert_eq!(&twice, &thrice);
    }

    /// **Property 4.** `decode -> re-encode` reproduces the input bytes for
    /// canonical input, at both manifest layers at once.
    ///
    /// The property is about the *encoder*, not a licence to re-encode:
    /// MVP-SPEC.md line 74 requires verifiers to hash the received bytes.
    /// What it proves is that the decode/encode pair loses nothing — if it
    /// did, a round-tripped manifest would carry a different `work_id` from
    /// the one that was signed.
    #[test]
    fn decode_then_reencode_reproduces_canonical_bytes(
        (envelope, body_bytes) in strategies::arb_manifest_bytes(CAPS)
    ) {
        let manifest = Manifest::decode(&envelope).expect("generated envelope decodes");

        // Layer 2: the borrowed body slice is byte-identical to what went in.
        prop_assert_eq!(manifest.body_bytes(), body_bytes.as_slice());
        // …and it is a *sub-slice* of the input, which is what makes the
        // zero-copy guarantee behind `work_id` structural rather than
        // conventional.
        prop_assert_eq!(manifest.encoded_bytes(), envelope.as_slice());

        // Layer 3: re-encoding the decoded body reproduces those bytes.
        let reencoded_body = encode_body(manifest.body().clone()).expect("re-encodes");
        prop_assert_eq!(&reencoded_body, &body_bytes);

        // …and re-wrapping reproduces the whole envelope.
        let reencoded = encode_envelope(&reencoded_body, manifest.signatures())
            .expect("re-encodes");
        prop_assert_eq!(&reencoded, &envelope);
    }

    /// Encoder output is canonical **at every nesting level**, not just at
    /// the top: the generic walker descends the whole tree, and a body whose
    /// inner `files` array carried a non-shortest head would fail here even
    /// though the outer envelope looked fine.
    #[test]
    fn every_layer_of_encoder_output_is_canonical(
        (envelope, body_bytes) in strategies::arb_manifest_bytes(CAPS)
    ) {
        prop_assert_eq!(check_canonical(&envelope), Ok(()));
        prop_assert_eq!(check_canonical(&body_bytes), Ok(()));
    }
}

// ───────────────────────────────────────────────────────────────────────
// The same four properties over `.sealproof` bundles
// ───────────────────────────────────────────────────────────────────────

proptest! {
    #![proptest_config(strategies::integration_test_config(0x5EED_F162, REGRESSIONS))]

    /// **Properties 1–4, bundle side.** `BundleV1` has no `PartialEq`
    /// (it borrows its input), so round-trip equality is stated where it is
    /// strongest anyway — on the **bytes**: decode, re-encode, byte-compare.
    /// A value-equality assertion could still hide a field the encoder drops;
    /// byte identity cannot.
    #[test]
    fn bundle_round_trips_and_re_encodes_byte_identically(
        bytes in strategies::arb_bundle_bytes(CAPS)
    ) {
        // Property 3: encoder output passes the generic canonicality pass.
        prop_assert_eq!(check_canonical(&bytes), Ok(()));

        // Properties 1 + 4: decode, re-encode, byte-compare.
        let bundle = BundleV1::decode(&bytes).expect("fixture bundles decode");
        let reencoded = encode_bundle(&bundle).expect("re-encodes");
        prop_assert_eq!(&reencoded, &bytes);

        // Property 2: encoding is a function of the value alone.
        let again = encode_bundle(&bundle).expect("re-encodes");
        prop_assert_eq!(&again, &reencoded);

        // The embedded manifest is a *sub-slice* of the bundle's own bytes,
        // never a copy — the structural form of the zero-copy guarantee that
        // `work_id` and `anchor_digest` are computed over received bytes
        // (registry §7.6.3). Asserted by address range, not by value: equal
        // contents would not prove it.
        let manifest = bundle.manifest_bytes();
        let base = bytes.as_ptr() as usize;
        let inner = manifest.as_ptr() as usize;
        prop_assert!(
            inner >= base && inner + manifest.len() <= base + bytes.len(),
            "the embedded manifest must borrow from the bundle input"
        );

        // …and all three layers decode together.
        Manifest::decode(manifest).expect("the embedded manifest decodes");
    }

    /// **Property 5, bundle layer.** The same twelve mutation classes over
    /// `.sealproof` bytes.
    ///
    /// A mutation landing on the manifest `bstr`'s *head* is a layer-1
    /// rejection; the scanner never descends into a `bstr` payload, so an
    /// embedded-manifest byte is never a target here — which is correct, since
    /// layer 1 treats those bytes as opaque by design (D78).
    #[test]
    fn mutating_a_bundle_fails_with_the_expected_class(
        bytes in strategies::arb_bundle_bytes(CAPS),
        kind in proptest::sample::select(MutationKind::ALL.as_slice()),
        pick in 0usize..64,
    ) {
        let Some(mutated) = strategies::mutate(&bytes, kind, pick) else {
            return Ok(());
        };
        prop_assume!(mutated != bytes);

        let err = match BundleV1::decode(&mutated) {
            Ok(_) => {
                prop_assert!(false, "{kind:?} produced an accepted bundle");
                return Ok(());
            }
            Err(e) => e,
        };
        prop_assert_eq!(
            err.code(),
            kind.expected_code(),
            "{:?} must be rejected as {}, got {}",
            kind,
            kind.expected_code(),
            err.code()
        );
        record(kind);
    }
}

// ───────────────────────────────────────────────────────────────────────
// Property 5: mutations fail with the correct class, and never panic
// ───────────────────────────────────────────────────────────────────────

proptest! {
    #![proptest_config(strategies::integration_test_config(0x5EED_F161, REGRESSIONS))]

    /// **Property 5, outer layer.** Every mutation of a canonical envelope is
    /// rejected with its class's exact `cbor-*` code.
    ///
    /// A mutation that finds no eligible site returns `None` and is skipped —
    /// `KeyReorder` needs a map with two entries, `InvalidUtf8` needs a
    /// non-empty `tstr`. Skips are why the coverage assertion exists: it is
    /// what proves the corpus really did reach every class.
    #[test]
    fn mutating_an_envelope_fails_with_the_expected_class(
        (envelope, _body) in strategies::arb_manifest_bytes(CAPS),
        kind in proptest::sample::select(MutationKind::ALL.as_slice()),
        pick in 0usize..64,
    ) {
        let Some(mutated) = strategies::mutate(&envelope, kind, pick) else {
            return Ok(());
        };
        prop_assume!(mutated != envelope);

        // Never a panic: `Manifest::decode` is total over arbitrary bytes.
        let err = match Manifest::decode(&mutated) {
            Ok(_) => {
                // A mutation the schema happens to accept is only legitimate
                // for the classes that can produce another valid encoding.
                // None of ours can, so this is a genuine failure.
                prop_assert!(false, "{kind:?} produced an accepted encoding");
                return Ok(());
            }
            Err(e) => e,
        };
        prop_assert_eq!(
            code_of(&err),
            kind.expected_code(),
            "{:?} must be rejected as {}, got {}",
            kind,
            kind.expected_code(),
            code_of(&err)
        );
        record(kind);
    }

    /// **Property 5, inner layer.** The same mutations applied to the *body*
    /// bytes and re-wrapped in a canonical envelope.
    ///
    /// This is the half that would go untested by mutating the envelope
    /// alone: an embedded `bstr` is opaque to the outer pass by design (spec
    /// line 74), so a corrupt body inside a well-formed envelope only
    /// surfaces when layer 3 runs its own strict pass. The code is the same
    /// `cbor-*` value — layer is pipeline context, not a rejection class —
    /// while the *variant* differs (`ManifestError::Body`), which is what
    /// `layer()` reports.
    #[test]
    fn mutating_a_body_fails_at_the_inner_layer_with_the_expected_class(
        (_envelope, body_bytes) in strategies::arb_manifest_bytes(CAPS),
        kind in proptest::sample::select(MutationKind::ALL.as_slice()),
        pick in 0usize..64,
    ) {
        let Some(mutated_body) = strategies::mutate(&body_bytes, kind, pick) else {
            return Ok(());
        };
        prop_assume!(mutated_body != body_bytes);
        let envelope = strategies::envelope_around(&mutated_body);

        let err = match Manifest::decode(&envelope) {
            Ok(_) => {
                prop_assert!(false, "{kind:?} produced an accepted body");
                return Ok(());
            }
            Err(e) => e,
        };
        prop_assert_eq!(
            code_of(&err),
            kind.expected_code(),
            "{:?} in the body must be rejected as {}, got {}",
            kind,
            kind.expected_code(),
            code_of(&err)
        );
        // The layer tag must say `Body`, never `Envelope`: the outer pass is
        // clean by construction here, and confusing the two would make every
        // inner-layer tamper row indistinguishable from an outer one.
        prop_assert_eq!(
            err.layer(),
            antseal_core::manifest::Layer::Body,
            "a body mutation must be reported at the body layer"
        );
        record(kind);
    }

    /// **Zero panics over arbitrary bytes.** Not a mutation property: the
    /// input is unconstrained, so almost every case is nonsense. What is
    /// asserted is only that the decoder is *total* — every outcome is a
    /// typed `Ok`/`Err`, never an abort, and never an `Err` outside the
    /// stable code universe.
    #[test]
    fn arbitrary_bytes_never_panic_the_decoder(
        bytes in proptest::collection::vec(any::<u8>(), 0..512)
    ) {
        let _ = check_canonical(&bytes);
        match Manifest::decode(&bytes) {
            Ok(_) => {}
            Err(e) => {
                let code = code_of(&e);
                prop_assert!(
                    code.starts_with("cbor-") || code.starts_with("manifest-"),
                    "unexpected code family: {code}"
                );
            }
        }
    }
}

// ───────────────────────────────────────────────────────────────────────
// The coverage assertion (F16 accept)
// ───────────────────────────────────────────────────────────────────────

/// **F16 accept: "mutation generators demonstrably cover every line-73
/// rejection class at least once".**
///
/// Runs the twelve classes over a fixed set of representative encodings
/// rather than reading the property blocks' shared counter, so the assertion
/// does not depend on test ordering or on proptest's threading — a coverage
/// claim that silently passed because another test had not run yet would be
/// worthless.
///
/// The classes deliberately **not** here, each with its reason:
///
/// - `cbor-malformed` — the defensive arm for states the head validation has
///   already made unreachable (a disagreement between the probe layer and the
///   pinned crate would be a codec bug). There is no input that reaches it.
/// - `cbor-nesting-too-deep` — **unreachable through a typed decode**
///   (decision D10 §6): every v1 field has a fixed type, so nesting a
///   container where a scalar belongs yields `cbor-unexpected-type` at level
///   one, never a depth violation at level nine. The depth guard lives in
///   `codec::decode::walk_item`, behind `check_canonical`, and is exercised
///   there; F15's over-deep fixture is a direct-call row for the same reason.
///   `MutationKind::TypeSubstitution` is the class that *does* fire, and this
///   test pins that substitution.
/// - `cbor-int-out-of-range` — a typed-reader class (`u64::MAX` read as
///   `i64`), not a canonicality class: no v1 field is read as `i64`, so no
///   mutation of a v1 encoding can reach it.
#[test]
fn every_mutation_class_is_reachable_on_a_real_encoding() {
    let (envelope, body_bytes) = strategies::canonical_manifest_pair();

    let mut missed = Vec::new();
    let mut hit = BTreeSet::new();
    for kind in MutationKind::ALL {
        let mut found = false;
        // Sweep the sites: some classes are only eligible at particular
        // positions, and a class that finds *no* site anywhere in either
        // layer of a full manifest is the failure this test exists to catch.
        'sites: for source in [&envelope, &body_bytes] {
            for pick in 0..64 {
                let Some(mutated) = strategies::mutate(source, kind, pick) else {
                    continue;
                };
                if &mutated == source {
                    continue;
                }
                let target = if std::ptr::eq(source, &envelope) {
                    mutated
                } else {
                    strategies::envelope_around(&mutated)
                };
                if let Err(e) = Manifest::decode(&target)
                    && e.code() == kind.expected_code()
                {
                    found = true;
                    hit.insert(kind);
                    break 'sites;
                }
            }
        }
        if !found {
            missed.push(kind);
        }
    }

    assert!(
        missed.is_empty(),
        "these mutation classes found no reachable site on a real manifest: {missed:?}"
    );
    assert_eq!(
        hit.len(),
        MutationKind::ALL.len(),
        "every class must be hit exactly once in the sweep"
    );
}

/// The twelve expected codes are pairwise distinct and every one of them is a
/// real `DecodeError` code — a class whose expected code no variant emits
/// could never fail, so the property above would be vacuous for it.
#[test]
fn mutation_classes_map_onto_distinct_real_codec_codes() {
    let codes: BTreeSet<&'static str> = MutationKind::ALL
        .iter()
        .map(|k| k.expected_code())
        .collect();
    assert_eq!(
        codes.len(),
        MutationKind::ALL.len(),
        "expected codes must be pairwise distinct"
    );

    let universe: BTreeSet<&'static str> = [
        DecodeError::Truncated { position: 0 },
        DecodeError::Malformed { position: 0 },
        DecodeError::IndefiniteLength { position: 0 },
        DecodeError::NonShortestInt { position: 0 },
        DecodeError::NonShortestLength { position: 0 },
        DecodeError::DuplicateMapKey { position: 0 },
        DecodeError::UnsortedMapKeys { position: 0 },
        DecodeError::InvalidUtf8 { position: 0 },
        DecodeError::TrailingBytes {
            position: 0,
            trailing: 1,
        },
        DecodeError::NestingTooDeep { position: 0 },
        DecodeError::IntOutOfRange { position: 0 },
    ]
    .iter()
    .map(DecodeError::code)
    .chain(["cbor-float", "cbor-simple-value", "cbor-tag"])
    .chain(["cbor-unexpected-type"])
    .collect();

    for code in &codes {
        assert!(
            universe.contains(code),
            "{code} is not a code any DecodeError variant emits"
        );
    }
}

// ───────────────────────────────────────────────────────────────────────
// F18 — the peek and the schema pass never disagree, on ANY input
// ───────────────────────────────────────────────────────────────────────
//
// F10 proves version dispatch case-wise, over an enumerated list of
// discriminants and mutations. What it cannot state is the *universal* form,
// which is what a third-party verifier actually relies on:
//
//   1. `peek_format_version(x) == Some(v)` with `v` outside
//      `SUPPORTED_VERSIONS`  =>  decode fails with that family's version
//      code — never a canonicality code, never an unknown-key code, so
//      "your file is from a newer antseal" can never be rendered as "your
//      file is corrupt";
//   2. decode *succeeds*  =>  the peek returned `Some(1)` — the peek and
//      the schema pass can never disagree about what the first key says.
//
// The one documented exception is stated, not hidden: D10 §5 makes the O(1)
// `input.len() > MAX_BUNDLE_BYTES` check the FIRST statement of
// `BundleV1::decode`, ahead of the peek, so an oversized artifact declaring
// an unsupported version is `bundle-too-large` (cheapest rejection wins).
// The property asserts that precondition rather than assuming the generator
// never reaches it.

/// A peek implementation. Parameterised so the property below can be re-run
/// against a deliberately mis-wired peek (`the_agreement_property_can_fail`),
/// which is what proves it is not vacuous.
type Peek = fn(&[u8]) -> Option<u64>;

/// Both directions of the F18 agreement, for one input. `Err` carries the
/// disagreement in reviewer-readable prose.
fn peek_decode_agreement(peek: Peek, input: &[u8]) -> Result<(), String> {
    use antseal_core::bundle::BundleV1;
    use antseal_core::format::SUPPORTED_VERSIONS;
    use antseal_core::manifest::ManifestBodyV1;

    let peeked = peek(input);

    // Direction 1, manifest half. `ManifestBodyV1::decode` reaches dispatch
    // with no pre-check of its own (the manifest's size cap binds the
    // *envelope*, one layer out), so this arm has no precondition.
    if let Some(v) = peeked
        && !SUPPORTED_VERSIONS.contains(&v)
    {
        match ManifestBodyV1::decode(input) {
            Ok(_) => {
                return Err(format!(
                    "a body declaring v{v} decoded, but v{v} is not supported"
                ));
            }
            Err(e) if e.code() != "manifest-unsupported-format-version" => {
                return Err(format!(
                    "a body declaring the unsupported v{v} was rejected as `{}` — an unsupported \
                     version must never be reported as a different fault",
                    e.code()
                ));
            }
            Err(_) => {}
        }

        // Direction 1, bundle half, with D10 §5's documented precondition.
        if input.len() as u64 <= antseal_core::codec::caps::MAX_BUNDLE_BYTES {
            match BundleV1::decode(input) {
                Ok(_) => {
                    return Err(format!(
                        "a bundle declaring v{v} decoded, but v{v} is not supported"
                    ));
                }
                Err(e) if e.code() != "bundle-unsupported-format-version" => {
                    return Err(format!(
                        "a bundle declaring the unsupported v{v} was rejected as `{}`",
                        e.code()
                    ));
                }
                Err(_) => {}
            }
        }
    }

    // Direction 2: acceptance implies the peek read the one supported
    // version. Stated over both families because each re-reads the
    // discriminant from the same bytes the peek read.
    if ManifestBodyV1::decode(input).is_ok() && peeked != Some(1) {
        return Err(format!(
            "a body decoded but the peek reported {peeked:?} rather than Some(1)"
        ));
    }
    if BundleV1::decode(input).is_ok() && peeked != Some(1) {
        return Err(format!(
            "a bundle decoded but the peek reported {peeked:?} rather than Some(1)"
        ));
    }
    Ok(())
}

/// The real peek — the same function `VersionDispatch::decode` consults.
fn real_peek(input: &[u8]) -> Option<u64> {
    antseal_core::format::peek_format_version(input)
}

/// A peek that reads the first key's value **without** the strict reader's
/// canonicality rules, by pattern-matching the two-byte prefix of a small
/// map. Used only by the test-of-the-test: it agrees with the real peek on
/// canonical input and disagrees on a non-shortest version head, which is
/// exactly the disagreement direction 1 must catch.
fn mis_wired_peek(input: &[u8]) -> Option<u64> {
    match input {
        // `map(n), key 0, 0x18 vv` — a NON-shortest one-byte-argument uint.
        // The real peek refuses this (the artifact is not canonical CBOR, so
        // its declared version is not trustworthy); this one reports it.
        [head, 0x00, 0x18, value, ..] if (0xA1..=0xB7).contains(head) => Some(u64::from(*value)),
        _ => real_peek(input),
    }
}

proptest! {
    #![proptest_config(strategies::integration_test_config(0x5EED_F162, REGRESSIONS))]

    /// **F18's property, over arbitrary bytes.** Most inputs are not
    /// versioned at all, which is the point: the peek must decline rather
    /// than guess, and neither direction may fire spuriously.
    #[test]
    fn peek_and_decode_agree_on_arbitrary_bytes(
        input in proptest::collection::vec(any::<u8>(), 0..96)
    ) {
        if let Err(why) = peek_decode_agreement(real_peek, &input) {
            prop_assert!(false, "{}", why);
        }
    }

    /// **F18's property, over REAL artifacts at an arbitrary version.** The
    /// arbitrary-bytes arm above almost never reaches direction 1's
    /// antecedent; this one reaches it every case, on the golden vectors'
    /// own bytes with only the discriminant rewritten (canonically, so the
    /// only fault is the version).
    #[test]
    fn peek_and_decode_agree_on_real_artifacts_at_any_version(version in any::<u64>()) {
        use antseal_core::test_util::tamper_rows_version as f18;

        let body = f18::body_at_version(version).expect("the golden body re-versions");
        if let Err(why) = peek_decode_agreement(real_peek, &body) {
            prop_assert!(false, "{}", why);
        }

        let manifest = f18::manifest_at_version(version).expect("the golden manifest re-versions");
        // The envelope carries no discriminant of its own, so the peek reads
        // `None` over it — the layer-3 body is where the version lives.
        prop_assert_eq!(real_peek(&manifest), None);
        let expect_ok = version == 1;
        prop_assert_eq!(Manifest::decode(&manifest).is_ok(), expect_ok);

        let bundle = f18::bundle_at_version(version).expect("the golden bundle re-versions");
        if let Err(why) = peek_decode_agreement(real_peek, &bundle) {
            prop_assert!(false, "{}", why);
        }
        prop_assert_eq!(real_peek(&bundle), Some(version));
    }
}

/// **Test of the test.** A peek that disagrees with the strict reader — here,
/// one that reads a *non-shortest* version head the real peek refuses —
/// makes the property fail, and fail with the disagreement named.
///
/// Without this, `peek_and_decode_agree_*` could pass by asserting nothing.
#[test]
fn the_agreement_property_can_fail() {
    // `{0: 2}` with the value written non-shortest: canonically invalid, so
    // the real peek declines and the decoder reports the canonicality fault.
    let non_shortest_v2: &[u8] = &[0xA1, 0x00, 0x18, 0x02];
    assert_eq!(real_peek(non_shortest_v2), None);
    assert!(
        peek_decode_agreement(real_peek, non_shortest_v2).is_ok(),
        "the real peek must agree with the decoder here"
    );

    // The mis-wired peek claims the artifact declares v2, so direction 1
    // demands the version code — and the decoder says `cbor-non-shortest-int`.
    let failure = peek_decode_agreement(mis_wired_peek, non_shortest_v2)
        .expect_err("a mis-wired peek must break the property");
    assert!(
        failure.contains("cbor-non-shortest-int"),
        "the failure must name the disagreement, got: {failure}"
    );
}
