//! C16 — the crypto golden-vector acceptance anchors
//! (`testdata/vectors/v1/crypto/`).
//!
//! The generic Q4 runner (`tests/vector_runner.rs`) already discovers and
//! executes every committed vector by walking the tree. These tests pin, in
//! addition, that **these exact files** exist at **these exact paths** with
//! **these exact kinds** — so a vector cannot silently vanish or be renamed
//! and still leave the runner green (the runner only fails on files it
//! *finds*; a deleted file is invisible to it). Together with Q6's
//! `FROZEN.sha256`, that closes the deletion hole.
//!
//! Every test name carries the reserved `vector_` marker, which opts the
//! suite into the three `cross-os-*` CI lanes (CONTRIBUTING.md, "Cross-OS
//! suite naming"): committed-vector byte stability must hold identically on
//! Linux, macOS, and Windows. This mirrors how C3's `hkdf_golden.rs` is
//! wired.
//!
//! # Provenance (why a green run is a cross-check, not a self-check)
//!
//! Each vector file's `expect` values were produced by an implementation
//! **independent of the Rust code they are executed against** — see
//! `testdata/vectors/v1/crypto/README.md` for the per-surface vehicle and
//! its justification. A vector generated by the code it validates proves
//! nothing; these were not.

use antseal_core::test_util::vectors::execute_vector_bytes;

/// Root of the committed crypto vectors (workspace-relative via the crate
/// manifest dir, so it holds on every OS and checkout location).
const CRYPTO_VECTORS: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../testdata/vectors/v1/crypto"
);

/// Execute one committed vector file by name, asserting its kind and the
/// number of entries it verified.
fn execute_committed(file: &str, expected_kind: &str, expected_items: usize) {
    let path = format!("{CRYPTO_VECTORS}/{file}");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
    let summary = execute_vector_bytes(&bytes, "v1").unwrap_or_else(|e| panic!("{path}: {e}"));
    assert_eq!(summary.kind, expected_kind, "{path}: unexpected kind");
    assert_eq!(
        summary.items, expected_items,
        "{path}: entry count changed — a committed vector was added or removed, \
         which after the Q6 freeze is a format event"
    );
}

/// C16 accept (commitments): the committed salted-commitment vectors —
/// generated by the independent Python reference implementation in
/// `testdata/vectors/v1/crypto/reference.py` — reproduce byte-identically
/// through this crate's public C6 API, with each entry's domain tag and
/// HKDF salt label re-checked against the frozen registry
/// (MVP-SPEC.md lines 79, 93–95).
#[test]
fn vector_committed_commitments_file_verifies() {
    execute_committed("commitments.json", "commitments", 12);
}
