#!/usr/bin/env bash
# Build the verifier page's WASM module and check it (R22).
#
#   ./scripts/wasm-pack-build.sh              build + every check
#   ./scripts/wasm-pack-build.sh --check      same, explicitly
#   ./scripts/wasm-pack-build.sh --build-only  build, no boundary comparison
#   ./scripts/wasm-pack-build.sh --self-test  the checks' own planted faults
#
# Exit 0 = the artifact exists, imports nothing outside the allow-list, and
# produces reports byte-identical to native over R9's corpus.
#
# ── The build is HERMETIC, and both flags are load-bearing ─────────────────
#
# MEASURED 2026-08-12 (R22's first act, D18 §7 P5 asked for exactly this):
# with every proxy variable pointed at a dead port, `wasm-pack build --release`
# still reached the network and downloaded a `wasm-opt` binary — binaryen
# **version 117, dated 2024-02-28** — into `~/.cache/.wasm-pack/`, then ran it.
# Nothing in this repository pins binaryen and `which wasm-opt` is empty, so
# that download is an unpinned, unreviewed program editing the artifact whose
# SHA-256 the page publishes about itself. It breaches D63 §5 R5's "no network
# access during the build" fence and docs/dependency-policy.md §5's
# "exact-pinned wherever installed".
#
#   --no-opt          does not run wasm-opt at all
#   --mode no-install does not fetch a wasm-bindgen-cli either; the one on
#                     PATH is used, and its version is asserted below
#
# Cost of the choice, measured on this 2-core host: 1.84 MB unoptimized
# against 1.53 MB optimized, and 2.8 s against 3 m 05 s. Re-enabling the
# optimizer is F29/R25's question and needs a PINNED binaryen first; it is not
# a flag an implementation lane may flip.
#
# ── The commit is SUPPLIED, never discovered ───────────────────────────────
#
# `crates/antseal-wasm/build.rs` reads ANTSEAL_SOURCE_COMMIT and stamps it into
# the build-info export D63 §5 R3's footer renders. This script is the one
# place that runs `git`; the crate itself runs no process, so a build from a
# source tarball with no `.git` still works and honestly reports `unknown`.
set -uo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo" || exit 1

note() { printf '\033[36m==>\033[0m %s\n' "$*"; }
die()  { printf '\033[31m::error::wasm-pack-build: %s\033[0m\n' "$*" >&2; exit 1; }

PKG="crates/antseal-wasm"
OUT_REL="../../target/wasm-pack/antseal-wasm"
OUT="target/wasm-pack/antseal-wasm"
CORPUS="target/antseal-wasm/boundary-corpus.json"
MODULE="${OUT}/antseal_wasm_bg.wasm"

# ── the pins (docs/dependency-policy.md §5) ────────────────────────────────
#
# Read from where they are DECLARED, never restated here: the crate pin from
# the root [workspace.dependencies] with the same line grep
# `scripts/wasm-toolchain-audit.sh` uses, and the tool pins from wherever an
# install line records them. A version literal copied into this script is a
# second copy that would agree today and drift afterwards (Q130).
crate_pin() {
  grep -E '^wasm-bindgen\b' Cargo.toml |
    sed -nE 's/.*"=([0-9]+\.[0-9]+\.[0-9]+)".*/\1/p' | head -n1
}
recorded_pin() {
  grep -rhoE "$1[^\n]*--version [0-9]+\.[0-9]+\.[0-9]+" .github/workflows scripts docs 2>/dev/null |
    sed -nE 's/.*--version ([0-9]+\.[0-9]+\.[0-9]+).*/\1/p' | sort -u
}
installed() { "$1" --version 2>/dev/null | sed -nE 's/^[^ ]+ ([0-9]+\.[0-9]+\.[0-9]+).*/\1/p' | head -n1; }

check_toolchain() {
  local want_bindgen have_bindgen want_pack have_pack
  want_bindgen="$(crate_pin)"
  [ -n "$want_bindgen" ] || die "no \`wasm-bindgen\` crate pin in the root Cargo.toml — the CLI must equal it (dependency-policy §5), so there is nothing to build against"
  have_bindgen="$(installed wasm-bindgen)"
  [ -n "$have_bindgen" ] || die "wasm-bindgen-cli is not on PATH. Install the pinned one: cargo install wasm-bindgen-cli --locked --version ${want_bindgen}"
  [ "$have_bindgen" = "$want_bindgen" ] ||
    die "wasm-bindgen-cli ${have_bindgen} is installed but the crate is pinned at ${want_bindgen} — glue generated by a mismatched CLI is a silent breakage (dependency-policy §5)"

  want_pack="$(recorded_pin wasm-pack)"
  [ -n "$want_pack" ] || die "no wasm-pack install line records an exact version anywhere — §5 requires exact-pinning wherever installed"
  [ "$(printf '%s\n' "$want_pack" | grep -c .)" -eq 1 ] ||
    die "wasm-pack is recorded at more than one version: $(printf '%s' "$want_pack" | tr '\n' ' ')"
  have_pack="$(installed wasm-pack)"
  [ -n "$have_pack" ] || die "wasm-pack is not on PATH. Install the pinned one: cargo install wasm-pack --locked --version ${want_pack}"
  [ "$have_pack" = "$want_pack" ] ||
    die "wasm-pack ${have_pack} is installed but ${want_pack} is the recorded pin (dependency-policy §5; the tool list IS part of the build's identity, D63 §7 rule 1)"

  printf '  wasm-bindgen %s (crate pin %s) · wasm-pack %s (recorded pin %s)\n' \
    "$have_bindgen" "$want_bindgen" "$have_pack" "$want_pack"
}

build() {
  local commit
  # `git` is this script's, never the crate's. A tree with no git still builds.
  commit="$(git rev-parse HEAD 2>/dev/null || printf 'unknown')"
  rm -rf "${OUT:?}"
  ANTSEAL_SOURCE_COMMIT="$commit" wasm-pack build "$PKG" \
    --release --target web --no-pack --no-opt --mode no-install \
    --out-dir "$OUT_REL" || return 1
  [ -f "$MODULE" ] || { printf '::error::wasm-pack reported success but %s does not exist\n' "$MODULE"; return 1; }
  printf '  %s — %s bytes, commit %s\n' "$MODULE" "$(wc -c <"$MODULE")" "$commit"
}

emit_corpus() {
  cargo run -q -p antseal-wasm --example boundary-emit --locked -- "$CORPUS"
}

cmd_check() {
  local build_only="$1" rc=0

  note "toolchain pins (dependency-policy §5)"
  check_toolchain || return 1

  note "build the shipped module (release, no wasm-opt, no tool download)"
  build || return 1

  note "import allow-list over the BUILT artifact (D18 §5 R7)"
  # Self-test first, always: a green allow-list proves nothing until it has
  # been seen to refuse something.
  node scripts/wasm-imports.mjs --self-test || return 1
  node scripts/wasm-imports.mjs "$MODULE" || return 1

  if [ "$build_only" -eq 1 ]; then
    note "--build-only: stopping before the boundary comparison"
    return 0
  fi

  note "emit the native side of R9's corpus"
  emit_corpus || return 1

  note "R9 vectors through the JS boundary, against native (Accept row 2)"
  node scripts/wasm-boundary.mjs "$OUT" "$CORPUS" || rc=1
  return "$rc"
}

# ── the tests of the tests ─────────────────────────────────────────────────
#
# Two planted faults, each proving that the check downstream of it can go red
# FOR THE RIGHT REASON. A nonzero exit is not the evidence — a crash exits
# nonzero too — so both arms match on the message.
cmd_self_test() {
  local fail=0 out status corrupt

  note "planted fault 1: a report byte changed on the native side"
  emit_corpus >/dev/null || die "the corpus could not be emitted, so nothing below proves anything"
  [ -f "$MODULE" ] || build >/dev/null || die "no module to compare against"
  corrupt="$(mktemp)"
  # Flip one byte inside the FIRST case's report hex. The boundary must report
  # a byte-position difference, not a load error and not a thrown export.
  node -e '
    const {readFileSync, writeFileSync} = require("node:fs");
    const corpus = JSON.parse(readFileSync(process.argv[1], "utf8"));
    const hex = corpus.cases[0].report_hex;
    const flipped = (hex[41] === "a" ? "b" : "a");
    corpus.cases[0].report_hex = hex.slice(0, 41) + flipped + hex.slice(42);
    writeFileSync(process.argv[2], JSON.stringify(corpus));
  ' "$CORPUS" "$corrupt" || die "could not plant the corrupt corpus"
  out="$(node scripts/wasm-boundary.mjs "$OUT" "$corrupt" 2>&1)"
  status=$?
  rm -f "$corrupt"
  if [ "$status" -eq 0 ]; then
    printf '::error:: the boundary comparison stayed GREEN with a planted report-byte difference — it is not comparing anything\n'; fail=1
  elif ! grep -q 'the report differs from native at byte' <<<"$out"; then
    printf '::error:: the boundary comparison went red for the WRONG reason:\n%s\n' "$(grep '::error::' <<<"$out" | head -3)"; fail=1
  else
    printf '  planted fault: one report byte flipped            -> RED (%s)\n' \
      "$(grep -o 'the report differs from native at byte [0-9]*' <<<"$out" | head -1)"
  fi

  note "planted fault 2: an unlisted host capability in the import table"
  out="$(node scripts/wasm-imports.mjs --self-test 2>&1)"
  status=$?
  if [ "$status" -ne 0 ]; then
    printf '::error:: the import allow-list self-test itself failed:\n%s\n' "$out"; fail=1
  else
    printf '%s\n' "$out" | sed 's/^/  /'
  fi

  [ "$fail" -eq 0 ] || return 1
  note "self-test PASS — both checks go red for their own reason"
}

case "${1:---check}" in
  --check | "") cmd_check 0 ;;
  --build-only) cmd_check 1 ;;
  --self-test)  cmd_self_test ;;
  *) die "usage: scripts/wasm-pack-build.sh [--check | --build-only | --self-test]" ;;
esac
